fail_on_violations: true

scss:
  config_file: .scss-lint.yml

jshint:
  enabled: false

eslint:
  enabled: true
  config_file: .eslintrc.json
  ignore_file: .eslintignore

ruby:
  enabled: false

rubocop:
  enabled: false
