# This action will run the tests locally using Chrome
name: localtests

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - master

jobs:
  localtests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      name: Set up NodeJS
      with:
        node-version: 18

    - name: Install
      run: npm install

    # Run the tests locally
    - name: Run the tests locally
      run: npm run test
